language: android
sudo: false
git:
  depth: 3 #将git depth设置相对小的值,加快构建速度
jdk:
  - oraclejdk8 #lambda表达式支持,如果工程中使用了rxJava等类库时添加
android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-android-support

script:
  - "./gradlew assembleDebug"

before_install:
- chmod +x gradlew
- gem install fir-cli
after_deploy:
  - fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"

notifications:
  webhooks:https://oapi.dingtalk.com/robot/send?access_token=a89c1543026b69693022764f0543fac45497e12bb393270e5f4c987a7376d286
